wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1695292530.741151
    t:
      1:
      - 1
      - 40
      - 41
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.13.1
      8:
      - 3
      - 5
epochs:
  desc: null
  value: 31
learning_rate:
  desc: null
  value: 0.5
